// @type {import('tailwindcss').Config} 

export default {
  theme: {
    extend: {
      colors: { 
        background: '#f4f4f4',
        primary: '#50d2c2',
        'primary-light': '#daf4f1',
        'primary-dark': '#15504a',
        'primary-2': '#daf4f1',
        'primary-3': '#ffcd1f',
        'primary-4': '#416d97',
        'neutral-white': '#fff',
        'neutral-black': '#092522',
        'pure-white': '#fff',
        'pure-black': '#000',
        'neutral-1': '#e7e7e7',
        'neutral-2': '#b3b6b5',
        'neutral-3': '#4a4a4a',
        'neutral-overlay': '#d9d9d9',
        'docs-light': '#e2edf6',
        'docs-med': '#a4cae9',
        'docs-dark': '#2888d7',
        'flashcards-light': '#f6eee2',
        'flashcards-med': '#efcd93',
        'video-light': '#f6e2e2',
        'video-med': '#e38585',
        'video-dark': '#bc3232',
        audio: '#4a4a4a',
        'pdf-light': '#ede2f6',
        'pdf-med': '#ccaee4',
        'pdf-dark': '#873fc2',
        'excel-light': '#ebf2df',
        'excel-med': '#bdd496',
        'ppt-light': '#fceadf',
        'ppt-med': '#e5ad8d',
        'icon-1': '#416d97',
        'icon-2': '#ffc009',
        'icon-3': '#fd7a7a',
        'icon-4': '#e2edf6',
        'icon-5': '#888',
        'type-1': '#092522',
        'type-2': '#7c7c7c',
        'type-3': '#bfbfbf',
        'type-4': '#4f79e5',
        'subject-1': '#f6f0e2',
        'subject-2': '#e2ecf6',
        'subject-3': '#f6e2e2',
        'subject-4': '#ece2f6',
        'subject-5': '#e2f6e8',
        'mc-study-1-light': '#f6e2f0',
        'mc-study-1-med': '#e7b0d6',
        'mc-study-1-dark': '#c83e80',
        'mc-study-2-light': '#ede2f6',
        'mc-study-2-med': '#ceb0e7',
        'mc-study-2-dark': '#823abb',
        'mc-study-3-light': '#e2f1fa',
        'mc-study-3-med': '#a7d4f0',
        'mc-study-3-dark': '#2875ad',
        'mc-study-4-light': '#eef8f6',
        'mc-study-4-med': '#bce4dc',
        'mc-study-4-dark': '#32b2a3',
        'success-primary': '#50d2c2',
        'success-secondary': '#eef8f6',
        'error-primary': '#f35353',
        'error-secondary': '#f8efef',
        'popup-gradient': 'linear-gradient(180deg, #e1eafe 36.79%, #faeee9)',
        'blue-gradient': 'linear-gradient(180deg, #e8f4fc, #e8f4fc 23.2%, #e8f4fc 47.49%, #fff 94.68%)',
        'orange-gradient': 'linear-gradient(180deg, #fcf2e8, #fdf5ee 23.2%, #fdf5ee 47.49%, #fff 94.68%)',
        'red-gradient': 'linear-gradient(180deg, #fce8e8, #fde9e9 23.2%, #fde9e9 47.49%, #fff 94.68%)',
        'ps-timeline-gradient': 'linear-gradient(180deg, #f4f4f4 65.95%, #fff 110%)',
        'interactive-border': '#28c3e1',
        'create-button-blue-hover': '#28c3e1',
        'metrics-button-dark-hover': '#3b4847',
        'endscreen-button-lightblue-hover': '#dcf9ff',
        'streak-dark': '#ff7c1d',
        'streak-light': '#ffeee2',
        'freeze-light': '#75e1ff',
        'revival-light': '#fe9099',
        'level-light': '#f0e9ff',
        'coin-light': '#fff3e5',
        'disabled-streak-button-hovered': '#efefef',
        'card-primary': '#fff',
        'card-tertiary': '#f3f3f3',
        'search-bar': '#f3f3f3',
        shadow: '#00000014',
        line: '#00000014',
        'reversed-button': '#000',
        inverted: '#000',
        highlight: '#ffface',

        // editor

        'editor-background': '#fff',
        'editor-neutral-1': '#e7e7e7',
        'editor-neutral-2': '#b3b6b5',
        'editor-neutral-3': '#4a4a4a',
        'editor-input-bar': '#fff',
        'editor-selected': '#efefef', 
      },
      
      fontFamily: {
        diatype: ['ABCDiatype', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
